substitutions:
  name: "comfoair"
  friendly_name: "ComfoAir"
  log_level: "DEBUG"

uart:
  # Communication channel with comfoair
  - id: !extend uart_bus
    tx_pin: 17
    rx_pin: 16
  # Communication channel with remote controller
  - id: !extend uart_proxy
    tx_pin: 19
    rx_pin: 18

packages:
  base: !include config/base.yaml
  debug: !include config/debug.yaml
  device: !include config/esp32-base.yaml
  bluetooth_proxy: !include config/bluetooth-proxy.yaml
  comfoair: !include config/comfoair-base.yaml
