esphome:
  name: comfoair
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  actions:
    - action: configure_fan_levels
      variables:
        exhaust_level_absent: int
        exhaust_level_low: int
        exhaust_level_mid: int
        exhaust_level_high: int
        supply_level_absent: int
        supply_level_low: int
        supply_level_mid: int
        supply_level_high: int
      then:
        - lambda: "id(comfoair_180).configure_fan_levels(exhaust_level_absent, exhaust_level_low, exhaust_level_mid, exhaust_level_high, supply_level_absent, supply_level_low, supply_level_mid, supply_level_high);"

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Local components
external_components:
  - source: components

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 20
  rx_pin: 21

button:
  - platform: template
    id: reset_filter_button
    name: "Reset Filter"
    on_press: 
      then:
        lambda: "id(comfoair_180).filter_reset();"

  - platform: restart
    id: restart_btn
    name: "Restart Controller"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Zurich

sensor:
  - platform: uptime
    type: timestamp
    name: "Last Boot Time"

switch:
  - platform: gpio
    pin: GPIO8
    name: "Status LED"
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

comfoair:
  id: comfoair_180
  climate_entity_id: comfoair_180
  name: "ComfoAir 180"
  uart_id: uart_bus
  # === Fan status ===
  intake_fan_speed:
    name: "Supply air level"
  exhaust_fan_speed:
    name: "Return air level"
  intake_fan_speed_rpm:
    name: "Intake fan RPM"
  exhaust_fan_speed_rpm:
    name: "Exhaust fan RPM"
  # === Valve status ===
  bypass_valve:
    name: "Bypass valve"
  bypass_valve_open:
    name: "Bypass open"
  #preheating_state:
  #  name: "Preheating state"
  #motor_current_bypass:
  #  name: "Motor current bypass"
  #motor_current_preheating:
  #  name: "Motor current preheating"
  # === Bypass control status ===
  #bypass_factor:
  #  name: "Bypass factor"
  #bypass_step:
  #  name: "Bypass step"
  #bypass_correction:
  #  name: "Bypass correction"
  summer_mode:
    name: "Summer mode"
  # === Temperature status ===
  # (not used)
  # === Sensor data (disabled in code) ===
  #enthalpy_temperature:
  #  name: "Enthalpy temperature"
  # === Ventilation level ===
  #return_air_level:
  #  name: "Return level"
  #supply_air_level:
  #  name: "Supply level"
  ventilation_level:
    name: "Ventilation level"
  supply_fan_active:
    name: "Supply fan active"
  #fanmode
  # === Faults ===
  filter_status:
    name: "Filter status"
  # === Temperatures ===
  outside_air_temperature:
    name: "Outside temperature"
  supply_air_temperature:
    name: "Supply temperature"
  return_air_temperature:
    name: "Return temperature"
  exhaust_air_temperature:
    name: "Exhaust temperature"
  #ewt_temperature:
  #  name: "EWT temperature "
  #reheating_temperature:
  #  name: "Reheating temperature"
  #kitchen_hood_temperature:
  #  name: "Kitchen hood temperature"
  # === Status (disabled in code) ===
  #preheating_present:
  #  name: "Preheating present"
  #bypass_present:
  #  name: "Bypass present"
  #type:
  #  name: "Type"
  #size:
  #  name: "Size"
  #options_present:
  #  name: "Options present"
  #fireplace_present:
  #  name: "fireplace_present"
  #kitchen_hood_present:
  #  name: "kitchen_hood_present"
  #postheating_present:
  #  name: "postheating_present"
  #postheating_pwm_mode_present:
  #  name: "postheating_pwm_mode_present"
  #p10_active:
  #  name: "P10 active"
  #p11_active:
  #  name: "P11 active"
  #p12_active:
  #  name: "P12 active"
  #p13_active:
  #  name: "P13 active"
  #p14_active:
  #  name: "P14 active"
  #p15_active:
  #  name: "P15 active"
  #p16_active:
  #  name: "P16 active"
  #p17_active:
  #  name: "P17 active"
  #p18_active:
  #  name: "P18 active"
  #p19_active:
  #  name: "P19 active"
  #p90_active:
  #  name: "P90 active"
  #p91_active:
  #  name: "P91 active"
  #p92_active:
  #  name: "P92 active"
  #p93_active:
  #  name: "P93 active"
  #p94_active:
  #  name: "P94 active"
  #p95_active:
  #  name: "P95 active"
  #p96_active:
  #  name: "P96 active"
  #p97_active:
  #  name: "P97 active"
  #enthalpy_present:
  #  name: "Enthalpy present"
  #ewt_present:
  #  name: "EWT present"
  # === Operation hours ===
  level0_hours:
    name: "Level 0 hours"
  level1_hours:
    name: "Level 1 hours"
  level2_hours:
    name: "Level 2 hours"
  level3_hours:
    name: "Level 3 hours"
  frost_protection_hours:
    name: "Frost protection hours"
  bypass_open_hours:
    name: "Bypass open hours"
  preheating_hours:
    name: "Preheating hours"
  filter_hours:
    name: "Filter hours"
  # === Preheating status (disabled in code) ===
  #preheating_valve:
  #  name: "Preheating valve"
  #frost_protection_active:
  #  name: "Frost protection active"
  #preheating_state
  #frost_protection_minutes:
  #  name: "Frost protection minutes"
  #frost_protection_level:
  #  name: "Frost protection level"
  # === Time delay (disabled in code) ===
  #bathroom_switch_on_delay_minutes:
  #  name: "Bathroom switch on delay minutes"
  #bathroom_switch_off_delay_minutes:
  #  name: "Bathroom switch off delay minutes"
  #l1_switch_off_delay_minutes:
  #  name: "L1 switch off delay minutes"
  #boost_ventilation_minutes:
  #  name: "Boost ventilation minutes"
  #filter_warning_weeks:
  #  name: "Filter warning weeks"
  #rf_high_time_short_minutes:
  #  name: "RF high time short minutes"
  #rf_high_time_long_minutes:
  #  name: "RF high time long minutes"
  #extractor_hood_switch_off_delay_minutes:
  #  name: "Extractor hood switch off delay minutes"
