substitutions:
  name: "sonoff-basic"
  friendly_name: "sonoff-basic"
  log_level: "DEBUG"

packages:
  base: !include config/base.yaml
  debug: !include config/debug.yaml
  device: !include config/esp8266.yaml

esphome:
  name_add_mac_suffix: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    on_press:
      then:
        - switch.toggle: switch_1

  - platform: status
    name: "My LS Status"

switch:
  - platform: gpio
    pin: GPIO12
    name: "Switch"
    id: switch_1

status_led:
  pin:
    number: GPIO13
    inverted: yes